# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
    value: {{ load.outputs.time }}
runs:
  using: 'composite'
  steps:
    - id: load
      run: |
        ${{ github.action_path }}/entrypoint.sh "${{ inputs.who-to-greet }}"
      shell: bash
