on: push
name: Run acceptance tests

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure 1Password Connect
        uses: edif2008/load-secrets-action/configure@v1.3.1 # 1password/load-secrets-action/configure@<version>
        with:
          connect-host: https://edf8-2001-1c00-b0b-dd00-3c41-1978-f314-b4f4.ngrok.io
          connect-token: ${{ secrets.OP_CONNECT_TOKEN }}
      - name: Load secrets
        id: load_secrets
        uses: edif2008/load-secrets-action@v1.3.1 # 1password/load-secrets-action@<version>
        env:
          DOCKER_USERNAME: op://acceptance-tests/docker/username
          DOCKER_PASSWORD: op://acceptance-tests/docker/password
          APP_TITLE: op://acceptance-tests/webapp/title
      - name: Push image to Docker Hub
        env:
          APP_TITLE: ${{ steps.load_secrets.outputs.APP_TITLE }}
        run: |
          docker login -u ${{ steps.load_secrets.outputs.DOCKER_USERNAME }} -p ${{ steps.load_secrets.outputs.DOCKER_PASSWORD }}
          docker build -t testopaction/example --build-arg APP_TITLE=$APP_TITLE.
          docker push testopaction/example
